// SPDX-License-Identifier: GPL-3.0
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.5.3. SEE SOURCE BELOW. !!
pragma solidity 0.8.7;

interface IDaoBeacon {
    struct ContractImpl {
        bytes32 contractName;
        address impl;
    }

    event DaoBeaconInit(string name, ContractImpl[] contractImpl);

    function implementation(bytes32) external view returns (address);

    function name() external view returns (string memory);
}

// THIS FILE WAS AUTOGENERATED FROM THE FOLLOWING ABI JSON:
/*
[{"inputs":[{"internalType":"string","name":"_name","type":"string"},{"components":[{"internalType":"bytes32","name":"contractName","type":"bytes32"},{"internalType":"address","name":"impl","type":"address"}],"internalType":"struct IDaoBeacon.ContractImpl[]","name":"_contractImpl","type":"tuple[]"}],"stateMutability":"nonpayable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":false,"internalType":"string","name":"name","type":"string"},{"components":[{"internalType":"bytes32","name":"contractName","type":"bytes32"},{"internalType":"address","name":"impl","type":"address"}],"indexed":false,"internalType":"struct IDaoBeacon.ContractImpl[]","name":"contractImpl","type":"tuple[]"}],"name":"DaoBeaconInit","type":"event"},{"inputs":[{"internalType":"bytes32","name":"","type":"bytes32"}],"name":"implementation","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"name","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"view","type":"function"}]
*/
