name: Deploy Pre-Dev
on:
  push:
    tags:    
      - 'v[0-9].[0-9]+.[0-9]+\-predev'

jobs:
  deploy-contracts:
    name: Deploy
    uses: ./.github/workflows/reusable-deploy-contracts.yml
    with:
      GIT_REF: ${{ github.ref_name }}
      CONTRACT_DEPLOY_NETWORK: rinkeby
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      RINKEBY_URL: ${{ secrets.RINKEBY_URL }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

  sync-subgraph:
    name: Sync Subgraph
    needs: deploy-contracts
    uses: ./.github/workflows/reusable-sync-subgraph.yml
    with:
      GIT_REF: ${{ github.ref_name }}
      DEPLOY_ENV: predev
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
