name: Deploy Dev
on:
  push:
    tags:
      - 'v[0-9].[0-9]+.[0-9]+\-dev\-ethereum'
      - 'v[0-9].[0-9]+.[0-9]+\-dev\-arbitrum'

concurrency:
  group: goerli-deployment

jobs:
  config-network-const:
    runs-on: ubuntu-latest
    steps:
      - uses: jungwinter/split@v2
        id: split
        with:
          msg: ${{ github.ref_name }}
          separator: '-'
      - name: Export Network Info
        id: network
        run: |
          echo "NETWORK=${{steps.split.outputs._2}}" >> $GITHUB_OUTPUT
    outputs:
      NETWORK: ${{ steps.network.outputs.NETWORK }}
  deploy-contracts-arbitrum:
    needs: config-network-const
    if: ${{ needs.config-network-const.outputs.NETWORK == 'arbitrum'}}
    name: Deploy Arbitrum
    uses: ./.github/workflows/reusable-deploy-contracts.yml
    with:
      GIT_REF: ${{ github.ref_name }}
      LIB_CONSTANT_NETWORK: arbitrum-goerli
      CONTRACT_DEPLOY_NETWORK: arbitrum-goerli-dev
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      RINKEBY_URL: ${{ secrets.RINKEBY_URL }}
      KOVAN_URL: ${{ secrets.KOVAN_URL }}
      GOERLI_URL: ${{ secrets.GOERLI_URL }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      GH_PAT: ${{ secrets.GH_PAT }}
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}      
      ARBITRUM_GOERLI_URL: ${{ secrets.ARBITRUM_GOERLI_URL }}
  deploy-contracts-ethereum:
    needs: config-network-const
    if: ${{ needs.config-network-const.outputs.NETWORK == 'ethereum'}}
    name: Deploy Ethereum
    uses: ./.github/workflows/reusable-deploy-contracts.yml
    with:
      GIT_REF: ${{ github.ref_name }}
      LIB_CONSTANT_NETWORK: goerli
      CONTRACT_DEPLOY_NETWORK: goerli-dev
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      RINKEBY_URL: ${{ secrets.RINKEBY_URL }}
      KOVAN_URL: ${{ secrets.KOVAN_URL }}
      GOERLI_URL: ${{ secrets.GOERLI_URL }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      GH_PAT: ${{ secrets.GH_PAT }}
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
      ARBITRUM_GOERLI_URL: ${{ secrets.ARBITRUM_GOERLI_URL }}
  sync-subgraph:
    name: Sync Subgraph
    needs: [deploy-contracts-ethereum,deploy-contracts-arbitrum]
    if: |
      always() &&
      (needs.deploy-contracts-ethereum.result == 'success' || needs.deploy-contracts-arbitrum.result == 'success')
    uses: ./.github/workflows/reusable-sync-subgraph.yml
    with:
      GIT_REF: ${{ github.ref_name }}
      DEPLOY_ENV: dev
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}

  sync-frontend:
    name: Sync Frontend
    needs: [deploy-contracts-ethereum,deploy-contracts-arbitrum]
    if: |
      always() &&
      (needs.deploy-contracts-ethereum.result == 'success' || needs.deploy-contracts-arbitrum.result == 'success')
    uses: ./.github/workflows/reusable-sync-frontend.yml
    with:
      GIT_REF: ${{ github.ref_name }}
      DEPLOY_ENV: dev
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}

  sync-discord-integration:
    name: Sync Discord Integration
    needs: [deploy-contracts-ethereum,deploy-contracts-arbitrum]
    if: |
      always() &&
      (needs.deploy-contracts-ethereum.result == 'success' || needs.deploy-contracts-arbitrum.result == 'success')
    uses: ./.github/workflows/reusable-sync-discord-integration.yml
    with:
      GIT_REF: ${{ github.ref_name }}
      DEPLOY_ENV: dev
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}

  sync-centralized-backend:
    name: Sync Centralized Backend
    needs: [deploy-contracts-ethereum,deploy-contracts-arbitrum]
    if: |
      always() &&
      (needs.deploy-contracts-ethereum.result == 'success' || needs.deploy-contracts-arbitrum.result == 'success')
    uses: ./.github/workflows/reusable-sync-centralized-backend.yml
    with:
      GIT_REF: ${{ github.ref_name }}
      DEPLOY_ENV: dev
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}