name: Deploy Contracts
on:
  push
  # push:
  #   tags:    
  #     - 'v[0-9].[0-9]+.[0-9]+\-dev'
  #     - 'v[0-9].[0-9]+.[0-9]+\-alpha'

env:
  GIT_REF: ${{ github.ref_name }} # either branch name or tag
  CONTRACT_DEPLOY_NETWORK: rinkeby
  RINKEBY_URL: ${{ secrets.RINKEBY_URL }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

jobs:
  deploy-contracts:
    name: Deploy Contracts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3.0.0
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm install
      
      - name: Compile Contracts
        run: npm run compile
      
      - name: Generate ABIs
        run: npx hardhat export # This generates json files into "abis/" folder
      
      - name: Deploy Contracts
        run: npx hardhat run scripts/1-deploy.js --network $CONTRACT_DEPLOY_NETWORK # Deploy contracts

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: deploy_${{ env.GIT_REF }}
          path: |
            abis/
            deploy/contract_address.json

      - name: Slack Notification
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "**Contract Deployment Success** \n**version**: ${{ env.GIT_REF }}\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

  sync-subgraph-repo:
    name: Syncrhonize with Subgraph Repo
    needs: deploy-contracts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Subgraph Repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/adam-subgraph
          ref: feat/AS-625/adding-auto-replace-subgraph-yaml-address # TODO
          token: ${{ secrets.GH_PAT }}      
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      
      - name: Install Dependencies
        run: yarn install

      - name: Fetch Deployment Info
        uses: actions/download-artifact@v3
        with:
          name: deploy_${{ env.GIT_REF }}
          path: ./deploy_artifacts

      - name: Replace ABIs
        run: cp ./deploy_artifacts/abis/* ./abis

      - name: Replace Subgraph Address
        run: | 
          yarn update-address -- 
            --Adam $(jq -r .adam ./deploy_artifacts/deploy/contract_address.json) 
            --GovernFactory $(jq -r .governFactory ./deploy_artifacts/deploy/contract_address.json)
      
      - name: Diff
        run: git diff
