name: Deploy Contracts
on:
  push:
    tags:    
      - 'v[0-9].[0-9]+.[0-9]+\-dev'

env:
  GIT_REF: ${{ github.ref_name }} # either branch name or tag
  CONTRACT_DEPLOY_NETWORK: rinkeby
  RINKEBY_URL: ${{ secrets.RINKEBY_URL }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

jobs:
  deploy-contracts:
    name: Deploy Contracts
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3.0.0
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm install
      
      - name: Compile Contracts # This also copies Machine ABIs to "abis/machine"
        run: |
          npm run compile && mkdir -p abis/machine && cp \
            artifacts/contracts/Adam.sol/Adam.json\
            artifacts/contracts/base/CommonBudgetApproval.sol/CommonBudgetApproval.json\
            artifacts/contracts/Dao.sol/Dao.json\
            artifacts/@openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata.sol/IERC20Metadata.json\
            artifacts/@openzeppelin/contracts/token/ERC721/ERC721.sol/ERC721.json\
            artifacts/contracts/Govern.sol/Govern.json\
            artifacts/contracts/GovernFactory.sol/GovernFactory.json\
            artifacts/contracts/Membership.sol/Membership.json\
            artifacts/contracts/TransferERC20BudgetApproval.sol/TransferERC20BudgetApproval.json\
            artifacts/contracts/UniswapBudgetApproval.sol/UniswapBudgetApproval.json\
            artifacts/contracts/LiquidPool.sol/LiquidPool.json\
            abis/machine

      - name: Generate Human Readable ABIs
        run: npx hardhat export-abi-human # This generates json files into "abis/human" folder
      
      - name: Deploy Contracts
        run: npx hardhat run scripts/1-deploy.js --network $CONTRACT_DEPLOY_NETWORK # Deploy contracts

      - name: Upload Deployment Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: deploy_${{ env.GIT_REF }}
          path: |
            abis/
            deploy/results.json

      - name: Slack Notification
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "text": "*Contracts Deployed*\n*version*: ${{ env.GIT_REF }}\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
  
  sync-frontend-repo:
    name: Syncrhonize with Frontend Repo
    needs: deploy-contracts
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Split Version Tag
        uses: jungwinter/split@v2
        id: split_version_tag
        with:
          msg: ${{ env.GIT_REF }}
          seperator: '-'

      - name: Checkout Frontend Repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/adam-frontend
          token: ${{ secrets.GH_PAT }}      
      
      - name: Fetch Deployment Info
        uses: actions/download-artifact@v3
        with:
          name: deploy_${{ env.GIT_REF }}
          path: ${{ runner.temp }}/deployment

      - name: Replace ABIs
        run: cp ${{ runner.temp }}/deployment/abis/human/* ./src/contracts

      - name: Setup Address as Env Vars
        run: |
          echo "REACT_APP_ADAM_CONTRACT_ADDRESS=$(jq -r .addresses.adam ${{ runner.temp }}/deployment/deploy/results.json)" >> $GITHUB_ENV
          echo "REACT_APP_OUTFLOW_CONTRACT_ADDRESS=$(jq -r .addresses.transferErc20BudgetApproval ${{ runner.temp }}/deployment/deploy/results.json)" >> $GITHUB_ENV
          echo "REACT_APP_SWAP_CONTRACT_ADDRESS=$(jq -r .addresses.uniswapBudgetApproval ${{ runner.temp }}/deployment/deploy/results.json)" >> $GITHUB_ENV

      - name: Replace Contract Address
        uses: mikefarah/yq@master
        with:
          cmd: |
            yq -i '
              .jobs.call-deploy-site.with.REACT_APP_ADAM_CONTRACT_ADDRESS = strenv(REACT_APP_ADAM_CONTRACT_ADDRESS) |
              .jobs.call-deploy-site.with.REACT_APP_OUTFLOW_CONTRACT_ADDRESS = strenv(REACT_APP_OUTFLOW_CONTRACT_ADDRESS) |
              .jobs.call-deploy-site.with.REACT_APP_SWAP_CONTRACT_ADDRESS = strenv(REACT_APP_SWAP_CONTRACT_ADDRESS)
            ' .github/workflows/deploy.${{ steps.split_version_tag.outputs._1 }}.yml
      
      - name: Make Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GH_PAT }}
          branch: autosync/contract_deploy_${{ env.GIT_REF }}
          title: Sync ${{ env.GIT_REF }} Contract Addresses and ABIs
          body: |
            Syncrhonizing Contract Addresses and ABIs from adam-contract-core
            Version: ${{ env.GIT_REF }}
            Ref. Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

          commit-message: "[Auto Commit] Sync ${{ env.GIT_REF }} deployment from adam-contract-core"
          reviewers: |
            redocsss

  sync-subgraph-repo:
    name: Syncrhonize with Subgraph Repo
    needs: deploy-contracts
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Split Version Tag
        uses: jungwinter/split@v2
        id: split_version_tag
        with:
          msg: ${{ env.GIT_REF }}
          seperator: '-'

      - name: Checkout Subgraph Repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/adam-subgraph
          token: ${{ secrets.GH_PAT }}      
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm install

      - name: Fetch Deployment Info
        uses: actions/download-artifact@v3
        with:
          name: deploy_${{ env.GIT_REF }}
          path: ${{ runner.temp }}/deployment

      - name: Replace ABIs
        run: cp ${{ runner.temp }}/deployment/abis/machine/* ./abis

      - name: Replace Subgraph Address
        run: | 
          jq -s '.[0].startBlock = .[1].block_number | 
            .[0].addresses.adam = .[1].addresses.adam |
            .[0].addresses.governFactory = .[1].addresses.governFactory |
            .[0]' \
            config/${{ steps.split_version_tag.outputs._1 }}.json ${{ runner.temp }}/deployment/deploy/results.json
      
      - name: Make Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GH_PAT }}
          branch: autosync/contract_deploy_${{ env.GIT_REF }}
          title: Sync ${{ env.GIT_REF }} Contract Addresses and ABIs
          body: |
            Syncrhonizing Contract Addresses and ABIs from adam-contract-core
            Version: ${{ env.GIT_REF }}
            Ref. Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

          commit-message: "[Auto Commit] Sync ${{ env.GIT_REF }} deployment from adam-contract-core"
          reviewers: |
            ayame30
            chikchoi6
