name: Deploy Contracts
on:
  push
  # push:
  #   tags:    
  #     - 'v[0-9].[0-9]+.[0-9]+\-dev'
env:
  CONTRACT_DEPLOY_NETWORK: rinkeby
  RINKEBY_URL: ${{ secrets.RINKEBY_URL }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

jobs:
  deploy-contracts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3.0.0
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm install
      
      - name: Compile Contracts
        run: npm run compile
      
      - name: Generate ABIs into artifacts
        run: npx hardhat export # This generates json files into "abis/" folder
      
      - name: Deploy Contracts
        run: npx hardhat run scripts/1-deploy.js --network $CONTRACT_DEPLOY_NETWORK # Deploy contracts