name: Deploy Predev
on:
  push:
    tags:    
      - 'v[0-9].[0-9]+.[0-9]+\-predev'

jobs:
  deploy-contracts:
    name: Deploy
    uses: ./.github/workflows/reusable-deploy-contracts.yml
    with:
      GIT_REF: ${{ github.ref_name }}
      LIB_CONSTANT_NETWORK: goerli
      CONTRACT_DEPLOY_NETWORK: goerli-predev
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      RINKEBY_URL: ${{ secrets.RINKEBY_URL }}
      KOVAN_URL: ${{ secrets.KOVAN_URL }}
      GOERLI_URL: ${{ secrets.GOERLI_URL }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
