name: Deploy Alpha
on:
  push:
    tags:    
      - 'v[0-9].[0-9]+.[0-9]+\-dev'

jobs:
  deploy-contracts:
    name: Deploy Contracts
    uses: ./.github/workflows/reusable/deploy-contracts.yml
    with:
      GIT_REF: ${{ github.ref_name }}
      CONTRACT_DEPLOY_NETWORK: rinkeby
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      RINKEBY_URL: ${{ secrets.RINKEBY_URL }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

  sync-subgraph:
    name: Deploy Contracts
    needs: deploy-contracts
    uses: ./.github/workflows/reusable/sync-subgraph.yml
    with:
      GIT_REF: ${{ github.ref_name }}
      DEPLOY_ENV: dev
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}

  sync-frontend:
    name: Deploy Contracts
    needs: deploy-contracts
    uses: ./.github/workflows/reusable/sync-frontend.yml
    with:
      GIT_REF: ${{ github.ref_name }}
      DEPLOY_ENV: dev
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}

