name: Deploy QA
on:
  push:
    tags:    
      - 'v[0-9].[0-9]+.[0-9]+\-qa'

concurrency:
  group: goerli-deployment

jobs:
  deploy-contracts:
    name: Deploy
    uses: ./.github/workflows/reusable-deploy-contracts.yml
    with:
      GIT_REF: ${{ github.ref_name }}
      LIB_CONSTANT_NETWORK: goerli
      CONTRACT_DEPLOY_NETWORK: goerli-qa
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      RINKEBY_URL: ${{ secrets.RINKEBY_URL }}
      KOVAN_URL: ${{ secrets.KOVAN_URL }}
      GOERLI_URL: ${{ secrets.GOERLI_URL }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      GH_PAT: ${{ secrets.GH_PAT }}
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
      ARBITRUM_GOERLI_URL: ${{ secrets.ARBITRUM_GOERLI_URL }}

  sync-subgraph:
    name: Sync Subgraph
    needs: deploy-contracts
    uses: ./.github/workflows/reusable-sync-subgraph.yml
    with:
      GIT_REF: ${{ github.ref_name }}
      DEPLOY_ENV: qa
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}

  sync-frontend:
    name: Sync Frontend
    needs: deploy-contracts
    uses: ./.github/workflows/reusable-sync-frontend.yml
    with:
      GIT_REF: ${{ github.ref_name }}
      DEPLOY_ENV: qa
      NETWORK: ethereum
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
  
  sync-centralized-backend:
    name: Sync Centralized Backend
    needs: deploy-contracts
    uses: ./.github/workflows/reusable-sync-centralized-backend.yml
    with:
      GIT_REF: ${{ github.ref_name }}
      DEPLOY_ENV: qa
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}

