name: Create and publish npm package

on:
    push:
        tags:
            - '[0-9].[0-9]+.[0-9]'

jobs:
    publish-package:
        runs-on: ubuntu-latest

        permissions:
            packages: write
            contents: read

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js 14.x
              uses: actions/setup-node@v3
              with:
                  node-version: 14.x

            - run: npm install

            - name: 'change version'
              uses: reedyuk/npm-version@1.1.1
              with:
                  version: ${{  github.ref_name }}

            - name: Add GPR token to .npmrc
              run: echo //npm.pkg.github.com/:_authToken=$GITHUB_TOKEN >> .npmrc
              env:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

            - name: Publish the package
              run: npm publish
