name: Create and publish npm package

on:
    push:
        tags:
            - '[0-9].[0-9]+.[0-9]'

jobs:
    publish-package:
        runs-on: ubuntu-latest

        permissions:
            packages: write
            contents: read

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3.0.0

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: 'npm'

            - name: Install Dependencies
              run: npm install

            - name: Compile Contracts # This also copies Machine ABIs to "abis/machine"
              run: |
                  npm run compile && mkdir -p abis/machine && cp \
                    artifacts/contracts/Adam.sol/Adam.json\
                    artifacts/contracts/base/CommonBudgetApproval.sol/CommonBudgetApproval.json\
                    artifacts/contracts/Dao.sol/Dao.json\
                    artifacts/@openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata.sol/IERC20Metadata.json\
                    artifacts/@openzeppelin/contracts/token/ERC721/ERC721.sol/ERC721.json\
                    artifacts/@openzeppelin/contracts/token/ERC721/extensions/IERC721Metadata.sol/IERC721Metadata.json\
                    artifacts/contracts/Govern.sol/Govern.json\
                    artifacts/contracts/Membership.sol/Membership.json\
                    artifacts/contracts/TransferERC20BudgetApproval.sol/TransferERC20BudgetApproval.json\
                    artifacts/contracts/TransferERC721BudgetApproval.sol/TransferERC721BudgetApproval.json\
                    artifacts/contracts/UniswapAnyTokenBudgetApproval.sol/UniswapAnyTokenBudgetApproval.json\
                    artifacts/contracts/Team.sol/Team.json\
                    abis/machine

            - name: Generate Human Readable ABIs
              run: npx hardhat export-abi-human # This generates json files into "abis/human" folder

            - name: 'change version'
              uses: reedyuk/npm-version@1.1.1
              with:
                  version: ${{  github.ref_name }}

            - name: Add GPR token to .npmrc
              run: echo //npm.pkg.github.com/:_authToken=$GITHUB_TOKEN >> .npmrc
              env:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

            - name: Publish the package
              run: npm publish
