name: pull-request-actions
on:
  pull_request:
    branches:    
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v3.0.0
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm run test
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps: 
      - uses: actions/checkout@v3.0.0
      - uses: crytic/slither-action@v0.1.1
        continue-on-error: true
        id: slither
        with:
          node-version: 16
          sarif: results.sarif
            - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.slither.outputs.sarif }}
  