on:
  workflow_call:
    inputs:
      GIT_REF:
        required: true
        type: string
      LIB_CONSTANT_NETWORK:
        required: true
        type: string
      CONTRACT_DEPLOY_NETWORK:
        required: true
        type: string
    secrets:
      GH_PAT:
        required: true

env:
  GIT_REF: ${{ inputs.GIT_REF }}
  LIB_CONSTANT_NETWORK: ${{ inputs.DEPLOYLIB_CONSTANT_NETWORK_ENV }}
  CONTRACT_DEPLOY_NETWORK: ${{ inputs.CONTRACT_DEPLOY_NETWORK }}

jobs:
  sync-subgraph-repo:
    name: Syncrhonize with Subgraph Repo
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Subgraph Repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/adam-subgraph
          token: ${{ secrets.GH_PAT }}      
      
      - name: Fetch Deployment Info
        uses: actions/download-artifact@v3
        with:
          name: deploy_${{ env.GIT_REF }}
          path: ${{ runner.temp }}/deployment

      - name: Replace ABIs
        run: cp ${{ runner.temp }}/deployment/abis/machine/* ./abis

      - name: Replace Subgraph Address
        run: | 
          jq -s '.[0].network = .[1].network | 
            .[0].startBlock = .[1].block_number | 
            .[0].addresses.adam = .[1].addresses.adam |
            .[0]' \
            config/${{ env.CONTRACT_DEPLOY_NETWORK }}.json ${{ runner.temp }}/deployment/deploy-results/results.json > temp.json \
            && mv temp.json config/${{ env.CONTRACT_DEPLOY_NETWORK }}.json
      
      - name: Make Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GH_PAT }}
          branch: autosync/contract_deploy_${{ env.GIT_REF }}
          title: Sync ${{ env.GIT_REF }} Contract Addresses and ABIs
          body: |
            Syncrhonizing Contract Addresses and ABIs from adam-contract-core
            Version: ${{ env.GIT_REF }}
            Ref. Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

          commit-message: "[Auto Commit] Sync ${{ env.GIT_REF }} deployment from adam-contract-core"
          reviewers: |
            chikchoi6
            ayame30
            lokwkin
