on:
  workflow_call:
    inputs:
      GIT_REF:
        required: true
        type: string
      DEPLOY_ENV:
        required: true
        type: string
    secrets:
      GH_PAT:
        required: true

env:
  GIT_REF: ${{ inputs.GIT_REF }}
  DEPLOY_ENV: ${{ inputs.DEPLOY_ENV }}

jobs:
  sync-centralized-backend-repo:
    name: Syncrhonize with CBE Repo
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout CBE Repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/adam-backend
          token: ${{ secrets.GH_PAT }}      
      
      - name: Fetch Deployment Info
        uses: actions/download-artifact@v3
        with:
          name: deploy_${{ env.GIT_REF }}
          path: ${{ runner.temp }}/deployment

      - name: Replace ABIs
        run: |
          cp ${{ runner.temp }}/deployment/abis/machine/Dao.json \
            ./abis

      - name: Replace Adam Address
        run: | 
          echo $(jq -s '.[0].adamAddress = .[1].addresses.adam | .[0]' \
            config/${{ env.DEPLOY_ENV }}.json ${{ runner.temp }}/deployment/deploy-results/results.json) > config/${{ env.DEPLOY_ENV }}.json
      
      - name: Make Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GH_PAT }}
          branch: autosync/contract_deploy_${{ env.GIT_REF }}
          title: Sync ${{ env.GIT_REF }} Contract Addresses and ABIs
          body: |
            Syncrhonizing Contract Addresses and ABIs from adam-contract-core
            Version: ${{ env.GIT_REF }}
            Ref. Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

          commit-message: "[Auto Commit] Sync ${{ env.GIT_REF }} deployment from adam-contract-core"
          reviewers: |
            eddy17c17c
