on:
  workflow_call:
    inputs:
      GIT_REF:
        required: true
        type: string
      CONTRACT_DEPLOY_NETWORK:
        required: true
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        required: true
      RINKEBY_URL:
        required: true
      PRIVATE_KEY:
        required: true

env:
  GIT_REF: ${{ inputs.GIT_REF }}
  CONTRACT_DEPLOY_NETWORK: ${{ inputs.CONTRACT_DEPLOY_NETWORK }}
  RINKEBY_URL: ${{ secrets.RINKEBY_URL }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

jobs:
  deploy-contracts:
    name: Deploy Contracts
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3.0.0
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm install
      
      - name: Compile Contracts # This also copies Machine ABIs to "abis/machine"
        run: |
          npm run compile && mkdir -p abis/machine && cp \
            artifacts/contracts/Adam.sol/Adam.json\
            artifacts/contracts/base/CommonBudgetApproval.sol/CommonBudgetApproval.json\
            artifacts/contracts/Dao.sol/Dao.json\
            artifacts/@openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata.sol/IERC20Metadata.json\
            artifacts/@openzeppelin/contracts/token/ERC721/ERC721.sol/ERC721.json\
            artifacts/contracts/Govern.sol/Govern.json\
            artifacts/contracts/GovernFactory.sol/GovernFactory.json\
            artifacts/contracts/Membership.sol/Membership.json\
            artifacts/contracts/TransferERC20BudgetApproval.sol/TransferERC20BudgetApproval.json\
            artifacts/contracts/TransferLiquidERC20BudgetApproval.sol/TransferLiquidERC20BudgetApproval.json\
            artifacts/contracts/UniswapBudgetApproval.sol/UniswapBudgetApproval.json\
            artifacts/contracts/LiquidPool.sol/LiquidPool.json\
            artifacts/contracts/Team.sol/Team.json\
            abis/machine

      - name: Generate Human Readable ABIs
        run: npx hardhat export-abi-human # This generates json files into "abis/human" folder
      
      - name: Deploy Contracts
        run: npx hardhat run scripts/1-deploy.js --network $CONTRACT_DEPLOY_NETWORK # Deploy contracts

      - name: Upload Deployment Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: deploy_${{ env.GIT_REF }}
          path: |
            abis/
            deploy/results.json

      - name: Slack Notification
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "text": "*Contracts Deployed*\n*version*: ${{ env.GIT_REF }}\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
  
