on:
  workflow_call:
    inputs:
      GIT_REF:
        required: true
        type: string
      DEPLOY_ENV:
        required: true
        type: string
    secrets:
      GH_PAT:
        required: true

env:
  GIT_REF: ${{ inputs.GIT_REF }}
  DEPLOY_ENV: ${{ inputs.DEPLOY_ENV }}

jobs:
  sync-frontend-repo:
    name: Syncrhonize with Frontend Repo
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Frontend Repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/adam-frontend
          token: ${{ secrets.GH_PAT }}      
      
      - name: Fetch Deployment Info
        uses: actions/download-artifact@v3
        with:
          name: deploy_${{ env.GIT_REF }}
          path: ${{ runner.temp }}/deployment

      - name: Replace SDK ABIs
        run: cp ${{ runner.temp }}/deployment/abis/human/* ./packages/adam-sdk/src/abis/v2

      - name: Setup Address as Env Vars
        run: |
          echo "REACT_APP_ADAM_CONTRACT_ADDRESS=$(jq -r .addresses.adam ${{ runner.temp }}/deployment/deploy-results/results.json)" >> $GITHUB_ENV \
          && echo "REACT_APP_NETWORK=$(jq -r .network ${{ runner.temp }}/deployment/deploy-results/results.json)" >> $GITHUB_ENV \

      - name: Replace Contract Address
        uses: mikefarah/yq@master
        with:
          cmd: |
            yq -i '
              .jobs.call-deploy-site.with.REACT_APP_ADAM_CONTRACT_ADDRESS = strenv(REACT_APP_ADAM_CONTRACT_ADDRESS) |
              .jobs.call-deploy-site.with.REACT_APP_NETWORK = strenv(REACT_APP_NETWORK)
            ' .github/workflows/deploy.${{ env.DEPLOY_ENV }}.yml
      
      - name: Make Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GH_PAT }}
          branch: autosync/contract_deploy_${{ env.GIT_REF }}
          title: Sync ${{ env.GIT_REF }} Contract Addresses and ABIs
          body: |
            Syncrhonizing Contract Addresses and ABIs from adam-contract-core
            Version: ${{ env.GIT_REF }}
            Ref. Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

          commit-message: "[Auto Commit] Sync ${{ env.GIT_REF }} deployment from adam-contract-core"
          reviewers: |
            redocsss

