name: test contracts

on:
  push:
    branches: [$default-branch]
    paths:
      - "contracts/**"
      - "test/**"
  pull_request:
    branches:
      - "*"
    paths:
      - "contracts/**"
      - "test/**"

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test_on_linux:
    name: Test on Ubuntu with Node 14
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          node-version: 14
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install
        run: npm install
      - name: Run tests
        run: npm run test